/** @type {import('tailwindcss').Config} */
const c = (v) => `rgb(var(--${v}) / <alpha-value>)`;

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Material 3 theme tokens (light + dark via CSS variables in index.css)
        'background':                  c('background'),
        'on-background':               c('on-background'),
        'surface':                     c('surface'),
        'surface-bright':              c('surface-bright'),
        'surface-dim':                 c('surface-dim'),
        'surface-variant':             c('surface-variant'),
        'surface-container-lowest':    c('surface-container-lowest'),
        'surface-container-low':       c('surface-container-low'),
        'surface-container':           c('surface-container'),
        'surface-container-high':      c('surface-container-high'),
        'surface-container-highest':   c('surface-container-highest'),
        'on-surface':                  c('on-surface'),
        'on-surface-variant':          c('on-surface-variant'),
        'inverse-surface':             c('inverse-surface'),
        'inverse-on-surface':          c('inverse-on-surface'),
        'primary':                     c('primary'),
        'on-primary':                  c('on-primary'),
        'primary-container':           c('primary-container'),
        'on-primary-container':        c('on-primary-container'),
        'primary-fixed':               c('primary-fixed'),
        'on-primary-fixed':            c('on-primary-fixed'),
        'inverse-primary':             c('inverse-primary'),
        'secondary':                   c('secondary'),
        'on-secondary':                c('on-secondary'),
        'secondary-container':         c('secondary-container'),
        'on-secondary-container':      c('on-secondary-container'),
        'error':                       c('error'),
        'on-error':                    c('on-error'),
        'error-container':             c('error-container'),
        'on-error-container':          c('on-error-container'),
        'outline':                     c('outline'),
        'outline-variant':             c('outline-variant'),
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      spacing: {
        'container-padding': '24px',
        'sidebar-width':     '260px',
        'sidebar-collapsed': '72px',
        'gutter':            '16px',
        'unit':              '8px',
        'margin-page':       '32px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-lg':      ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':      ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm':     ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'data-tabular': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-md':  ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg':  ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'display-lg':   ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      transitionProperty: {
        'sidebar': 'width, margin-left, padding',
      },
    },
  },
  plugins: [],
};
